### ISSUE TITLE
Official NPM package link on GitHub

### ISSUE THREAD

**Issue by stefreak** [homebridge/node-pty-prebuilt-multiarch#31]
### Analysis

On github the NPM package link points to [node-pty-prebuilt-multiarch](https://www.npmjs.com/package/node-pty-prebuilt-multiarch) which was last updated 2 years ago

The github action seems to publish to [@homebridge/node-pty-prebuilt-multiarch](https://www.npmjs.com/package/@homebridge/node-pty-prebuilt-multiarch)

Which one is the official package? Should the link be updated? Have the credentials to the other account been lost? (If yes, that should be announced as a security advisory / CVE so that people switch to the new package)

### Expected Behavior

I expect the link on github to point to the official package that gets updated regularly.

### Steps To Reproduce

Click on the website link on github:
<img width="1767" alt="Screenshot 2023-11-08 at 09 23 47" src="https://github.com/homebridge/node-pty-prebuilt-multiarch/assets/139624/793679d7-596a-4aad-9b3c-b530a3e859bc">

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

N/A

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
@stefreak We moved this into the Homebridge domain earlier this year, and the homebridge collaborator team has taken over ongoing support for the package.   Hence the recent updates etc.  The original author is still around, he is just occupied with other things these days.

Tks for pointing out the incorrect link, we have corrected it.

**Comment by stefreak** [comment]
Awesome, thanks a lot!
