### ISSUE TITLE
Support for Node v22 / ABI version 127

### ISSUE THREAD

**Issue by stefreak** [homebridge/node-pty-prebuilt-multiarch#42]
### Current Situation

Would be nice to support Node v22 / ABI version 127

### Proposed Change

Add builds for ABI version 127

**Comment by NorthernMan54** [comment]
Tks, will take a look at this tomorrow AM

**Comment by bwp91** [comment]
Builds for windows/node22 are still failing, see UI job runner here:

https://github.com/homebridge/homebridge-config-ui-x/actions/runs/9242175802/job/25424644249

**Comment by NorthernMan54** [comment]
Resolved
